name: Feature Request
description: Suggest an idea for this project
title: "feat: "
labels: ["t: feature", "s: pending-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the project and taking the time to fill out this feature report!

  - type: textarea
    id: problem
    attributes:
      label: Describe the problem
      description: Please provide a clear and concise description the problem this feature would solve. The more information you can provide here, the better.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the proposed solution
      description: Please provide a clear and concise description of what you would like to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Please provide a clear and concise description of any alternative solutions or features you have considered.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information
      description: Add any other context or screenshots about the feature request here.
